config/routes.rb
Rails.application.routes.draw do
  get 'bienvenido/index'
  resources :articulos
  

   root 'bienvenido#index'

end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @articulos = Articulo.all
  end
  
  def show
    @articulos = Articulo.find(params[id])
  end
  def new
  end
  #abreviar
  
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  
  
  def create
  @articulo = Articulo.new(articulo_params)
 
  @articulo.save
  redirect_to @articulo
end
 
  def show
    @articulo =Articulo.find(params[:id])
  end
  
  def new
  end
  
  
private
  def articulo_params
    params.require(:articulo).permit(:titular, :contenido)
  end
 
 
  
  
end
  

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def new 
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/views/articulos/index.html.erb
<h1>Listando Artículos</h1>
 
<table>
  <tr>
    <th>Titular</th>
    <th>Contenido</th>
  </tr>
 
  <% @articulos.each do |articulo| %>
    <tr>
      <td><%= articulo.titular %></td>
      <td><%= articulo.contenido %></td>
    </tr>
  <% end %>
</table>

app/views/articulos/new.html.erb
<h1>
  nuevo articulo
</h1>

  <%= form_for :articulo, url: articulos_path do |f| %>
  <p>
    <%= f.label :titular %><br>
    <%= f.text_field :titular %>
  </p>
 
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit 'Guardar Artículo' %>
  </p>
<% end %>

  

app/views/articulos/show.html.erb
<p>
  <strong>titular:</strong>
  <%= @articulo.titular %>
</p>

<p>
  <strong>contenido:</strong>
  <%= @articulo.titular %>
</p>

<p>
  <strong>titular:</strong>
  <%= @articulo.titular %>
</p>

<p>
  <strong>contenido:</strong>
  <%= @articulo.titular %>
</p>

<p>
  <strong>titular:</strong>
  <%= @articulo.titular %>
</p>

<p>
  <strong>contenido:</strong>
  <%= @articulo.titular %>
</p>

app/views/bienvenido/index.html.erb
<h1>Hola Rails</h1>
<p>ensayo de blog</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>